### ISSUE TITLE
Navigation buttons should use css

### ISSUE THREAD

**Issue by inalyricalcoma** [buildinternet/supersized#1]
Hi, first of all thank you for you great work - this a really nice plugin

Today I discovered navigation buttons src is handled by javascript - even if it's pretty simple to overwrite images in the default image folder, it actually breaks with SEF urls.

Why don't you use css background images for navigation buttons? this way you can both provide a default setup which doesn't need to be modified (you are currently providing a .css and an image folder already), and an easy way to customize your images (either by overwriting the image or modifying css) while keeping compatibilty with SEF urls

Thanks and regards,

**Comment by samdunn** [comment]
Thanks for bringing this up,

Ultimately I'll probably make this shift in a coming update, but I've tried to avoid breaking people's existing setups. If you're worried about being able to make SEF friendly URLs, you can bypass the image replacement by applying the "#prevslide" and "#nextslide" IDs to an 'a' tag rather than directly to an image. You can then put whatever you want inside this tag.

Although I admit I don't see the need for a button to have a SEF URL, I'll make a note and potentially transition this over in the future.

**Comment by inalyricalcoma** [comment]
Thank you for your reply!

I'll use the IDs with the 'a' tag then, didn't know that could be done

The button itself has no reason for being SEF, but the gallery can be placed in different pages, i.e. the same code should work on both "www.yoursite.com/example.html" and "www.yousite.com/pages/codes/demo.html" - which actually won't happen with a single image_path inside the .js

I'll probably use your suggestion for now on, but meanwhile i added an option 'image_path' so i could easily correct the url without editing the .js

<i>var image_path = options.image_path;</i>

my suggestion is to implement this anyway, this can help in keeping things straight for someone who needs to handle different templates in a single website, for example

thank you again for your good work
