### ISSUE TITLE
Image starts at 50% of screen in Chrome

### ISSUE THREAD

**Issue by janegbert** [buildinternet/supersized#19]
Sometimes when I watch my website in Chrome, the images don't stick to the top of the browser but get rendered at 50% of the screen. Try here: http://www.janegbert.nl. I see the same effect with the Supersized demo.

**Comment by samdunn** [comment]
Hello there,

First off, sharp website - I like what you've done.

In the history of Supersized, the 50% down the screen bug happened in 3.1.3 whenever the image wasn't loaded before being transitioned to. In that case, it would hop back up to the proper position once fully downloaded. In looking at your site on Chrome, I've yet to come across the problem, which also happens on the demo?

Do you have any pointers as to how I might go about emulating the problem so I can take a look?

**Comment by samdunn** [comment]
Upon further review, you might just be referring to vertical_center, which is an option that can be turned off.

**Comment by jrocho** [comment]
I'm having the same problem with Chrome. It happens when switching to different pages on the site, not when reloading an already loaded page. If vertical_center is 'true' I get a 50% black on top sometimes. When it is set to 'false' I get a black area at the bottom of the page.

Example: http://scenology.eu/de/
