### ISSUE TITLE
Bug with Supersized 3.2.4 - picture not loaded

### ISSUE THREAD

**Issue by johnvuko** [buildinternet/supersized#37]
I found a bug with Supersized 3.2.4, i test on your version (http://buildinternet.com/project/supersized/slideshow/3.2/demo.html).

For see the bug :
- load the page http://buildinternet.com/project/supersized/slideshow/3.2/demo.html
- stop playing
- click on a bullet (prefer the last) and immediately after click on the LEFT arrow

And we don't see the picture and there is no error in my javascript debugger, i test with Chrome 14, Firefox 3.6.

**Comment by ganarajpr** [comment]
I am facing the same issue. 

Any updates on this ?

**Comment by johnvuko** [comment]
No, i don't have the time for this, i decided to use flash for my gallery :(

**Comment by richardhomewood** [comment]
I'm facing what appears to be a similar problem, in a slightly different situation.

It happens when the api.goTo() is called on a slide which is > 3

For example:

http://dev.richardhomewood.co.uk/portfolio/#/surestart-section
- here api.goTo() is called on slide number 4 and the prevslide does not load correctly. This occurs for slides 5 and 6 as well.

http://dev.richardhomewood.co.uk/portfolio/#/manchester-section
- here api.goTo() is called on slide number 3 and the prevslide does load correctly.

Any help on this would be greatly appreciated.

Cheers,
Rich

**Comment by samdunn** [comment]
Hey Guys,

I just pushed through 3.2.6 which should address this issue - thanks so much for bringing this up (and your patience)
