### ISSUE TITLE
INTERNET EXPLORER :(

### ISSUE THREAD

**Issue by unsuprise** [buildinternet/supersized#55]
http://artelivinginterior.com/index.php?gallery

If using Internet explorer can not work. 

Pllisss Help Me :(

**Comment by tada70** [comment]
Hi Unsurpised,

I have had the same problem, in chrome it was woking nice, IE8 failed.
After checking http://www.buildinternet.com/project/supersized/faq.html#q-1 the problem was not gone.
After a litte test i have found out that the problem was the name of the files.
example; "test 1.jpg" was not good in IE8, after changing it in "test_1.jpg" the problem was solved.

I hope this solves your problem.

**Comment by unsuprise** [comment]
thanks tada70,  but still error. "test 1.jpg" was not good in IE8, after changing it in "test_1.jpg" :((

**Comment by unsuprise** [comment]
Sorry, I've managed .. Thanks tada70

**Comment by samdunn** [comment]
On the link provided you are not using the latest Supersized - I would suggest updating to the latest.
