### ISSUE TITLE
Too complicated implementation

### ISSUE THREAD

**Issue by veke** [buildinternet/supersized#84]
I spent hour and a half to get finally working version to my site of this wonderfull plugin.
This separation of core and slideshow versions is misleading. The documentation is somehow incomplete.
The basic api functions should be implemented in the core version too...like any other jquery plugins work...(fancybox, cycle etc...)

**Comment by samdunn** [comment]
I can certainly update the docs to better explain the difference between core and slideshow.

The core version doesn't any any API functions in the interest of keeping things light and since the functions almost all pertain to slideshow functionality. Core is meant for when you only want the background resized.
